create sequence hibernate_sequence start with 1 increment by 1
create table customer (customer_id bigint generated by default as identity, birth_city varchar(255), birth_date date not null, country varchar(255), last_name varchar(255) not null, marital_status varchar(255) not null, name varchar(255) not null, profession varchar(255), gender_id varchar(255), identification_id bigint, primary key (customer_id))
create table gender (code varchar(255) not null, description varchar(255), primary key (code))
create table identification (id bigint not null, expedition_city varchar(255), expedition_date date, number_identification varchar(255), identification_type varchar(255), primary key (id))
create table identification_type (code varchar(255) not null, identification_type varchar(255), primary key (code))
alter table customer add constraint UK_ig2c18ll9bnhdy4317spvn0ml unique (identification_id)
alter table gender add constraint UK_h8nm41i9isuxfb4yqocspv7gh unique (description)
alter table identification add constraint UK_q7vfhck9doroyucyuq6bldo2r unique (number_identification)
alter table customer add constraint FK1lt23ie2trgs1r42hqyhliedv foreign key (gender_id) references gender
alter table customer add constraint FKs9arc8fa2utirshtdcjj0scqi foreign key (identification_id) references identification
alter table identification add constraint FKcy6wwme713x1mwj9q8tivu8f8 foreign key (identification_type) references identification_type
